import { resolve } from 'node:path';
import { afterAll, describe, expect, it } from 'vitest';
import { grade, resolveDataset } from '@codeadda/core';
import { loadLabFromDir } from '@codeadda/content-loader/node';
import { PgliteEngine } from '@codeadda/engine-pglite';

const lab = loadLabFromDir(resolve(import.meta.dirname, '../content/postgres'));
const lessons = lab.lessons.flatMap((c) => c.items);
const byId = (id: string) => {
  const l = lessons.find((x) => x.id === id);
  if (!l) throw new Error(`no lesson ${id}`);
  return l;
};

describe('PostgreSQL lab answer checks', () => {
  const engine = new PgliteEngine();
  afterAll(() => engine.dispose());
  const check = (id: string, query: string) => grade(engine, byId(id), resolveDataset(lab, byId(id)), query);

  it('accepts equivalent answers to beginner build lessons', async () => {
    expect((await check('create-table', 'create table menu (price numeric(6,2), name text, id int);')).pass).toBe(true);
    expect((await check('alter-table', 'ALTER TABLE menu   ADD COLUMN is_veg bool;')).pass).toBe(true);
    expect((await check('drop-table', 'DROP TABLE IF EXISTS old_menu;')).pass).toBe(true);
  });

  it('never passes a no-op for any state or custom lesson', async () => {
    const graded = lessons.filter((l) => l.check === 'state' || l.check === 'custom');
    expect(graded.length).toBeGreaterThanOrEqual(15);
    const passed: string[] = [];
    for (const l of graded) if ((await grade(engine, l, resolveDataset(lab, l), 'SELECT 1;')).pass) passed.push(l.id);
    expect(passed).toEqual([]);
  });
});

describe('stricter checks', () => {
  const engine = new PgliteEngine();
  afterAll(() => engine.dispose());
  const check = (id: string, query: string) => grade(engine, byId(id), resolveDataset(lab, byId(id)), query);

  it('unique-check requires UNIQUE(name) and CHECK price > 0 exactly', async () => {
    const pass = [
      'ALTER TABLE menu ADD UNIQUE (name), ADD CHECK (price > 0);',
      'ALTER TABLE menu ADD CONSTRAINT name_once UNIQUE (name), ADD CONSTRAINT price_positive CHECK (price > 0);',
      'ALTER TABLE menu ADD UNIQUE (name), ADD CHECK (0 < price);',
      'ALTER TABLE menu ADD UNIQUE (name), ADD CHECK (price > 0.00);',
    ];
    for (const q of pass) expect((await check('unique-check', q)).pass, q).toBe(true);
    const fail = [
      'ALTER TABLE menu ADD UNIQUE (name), ADD CHECK (price >= 0);',
      'ALTER TABLE menu ADD UNIQUE (name), ADD CHECK (price > 1);',
      'ALTER TABLE menu ADD UNIQUE (name), ADD CHECK (id > 0);',
      'ALTER TABLE menu ADD CHECK (price > 0);',
      'ALTER TABLE menu ADD UNIQUE (name);',
      'SELECT 1;',
    ];
    for (const q of fail) expect((await check('unique-check', q)).pass, q).toBe(false);
  });

  it('identity-vs-serial requires an always-generated integer primary key', async () => {
    const pass = [
      'CREATE TABLE coupons (id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY, code text);',
      'CREATE TABLE coupons (code text, id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY);',
      'CREATE TABLE coupons (id integer GENERATED ALWAYS AS IDENTITY, code text, CONSTRAINT coupons_pk PRIMARY KEY (id));',
    ];
    for (const q of pass) expect((await check('identity-vs-serial', q)).pass, q).toBe(true);
    const fail = [
      'CREATE TABLE coupons (id integer GENERATED ALWAYS AS IDENTITY, code text);',
      'CREATE TABLE coupons (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code text);',
      'CREATE TABLE coupons (id serial PRIMARY KEY, code text);',
      'SELECT 1;',
    ];
    for (const q of fail) expect((await check('identity-vs-serial', q)).pass, q).toBe(false);
  });
});

